[package]
name = "c0check"
version = "0.1.0"
authors = ["Ishan Bhargava <{ID}+{username}@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
thiserror = "1.0.23"
logos = "0.11.4"
nix = "0.19.0"
